### PR TITLE
Replace authToken with apiKey

### PR DESCRIPTION
**Pull request by rradhakris-vail**

### CODE REVIEW

**Review by apvail — APPROVED** [review]

**Comment by csamatas** [comment]
It looks like logout might still reference auth token

**Comment by apvail** [comment]
> It looks like logout might still reference auth token

Line number?

**Comment by csamatas** [comment]
ReadMe and Line 18 of Logout.js

**Comment by csamatas** [comment]
> > It looks like logout might still reference auth token
> 
> Line number?

See comment below

**Comment by apvail** [comment]
> ReadMe and Line 18 of Logout.js

Ah, yes. Good catch.

https://github.com/FreeClimbAPI/freeclimb-cli/blob/FREECLI-218J/src/commands/logout.ts#L18
https://github.com/FreeClimbAPI/freeclimb-cli/blame/FREECLI-218J/README.md#L59

**Review by apvail — CHANGES_REQUESTED** [review]
As Kay points out, a few spots were missed

https://github.com/FreeClimbAPI/freeclimb-cli/blob/FREECLI-218J/src/commands/logout.ts#L18
https://github.com/FreeClimbAPI/freeclimb-cli/blame/FREECLI-218J/README.md#L59

**Pull request merged**
